export const THEMES = [
  ["chat", "chien"],
  ["king kong", "godzilla", "yeti", "dinosaure"],
  ["mario", "luigi", "waluigi", "wario", "peach", "toad", "yoshi"],
  ["iphone", "android"],
  ["voiture", "moto", "car", "bus", "train", "tram"],
  ["tennis", "badminton", "volleyball"],
  ["football", "handball"],
  ["roller", "patin"],
  ["skateboard", "snowboard"],
  ["souris", "rat", "hamster"],
  ["montagne", "volcan", "colline"],
  ["game of thrones", "seigner des anneaux"],
  ["arbre", "buisson", "fleur", "herbe"],
  ["burger", "frites", "pizza", "hotdog"],
  ["mayonnaise", "ketchup", "moutarde"],
  ["main", "pied", "bras", "jambe"],
  ["bouche", "dent", "langue"],
  ["cuillere", "fourchette", "couteau"],
  ["verre", "bouteille", "bouchon"],
  ["coca cola", "pepsi", "fanta", "orangina", "oasis", "ice tea"],
  ["vin blanc", "vin rouge"],
  ["romeo", "juliette"],
  ["jedi", "sith"],
  ["sel", "poivre", "sucre"],
  ["roi", "reine", "prince", "princesse"],
  ["requin", "baleine", "orque", "dauphin"],
  ["babord", "tribord"],
  ["ete", "hiver", "automne", "printemps"],
  ["pikachu", "bulbizarre", "salameche", "carapuce"],
  ["melenchon", "lepen", "macron"],
  ["spotify", "deezer"],
  ["ironman", "captain america", "spiderman", "thor", "hulk"],
  ["guitare", "basse", "ukulele"],
  ["pantalon", "short", "jupe"],
  ["tshirt", "pull", "robe"],
  ["casquette", "bonnet", "chapeau"],
  [
    "paris",
    "marseilles",
    "le havre",
    "rouen",
    "lyon",
    "strasbourg",
    "bordeaux",
    "toulouse",
  ],
  ["batman", "robin", "joker", "catwoman", "harley quinn"],
  ["crayon", "stylo", "gomme", "regle", "trousse", "cahier"],
  ["vache", "taureau"],
];
